### ISSUE TITLE
Double Buffering Option

### ISSUE THREAD

**Issue by bkoropoff** [ramapcsx2/gbs-control#2]
It would be great to have a double buffering mode to eliminate screen tearing (at the cost of occasional duplicate/dropped frames).  I've attempted to enable it by poking the appropriate registers, but all setting combinations I've tried result in garbled output.  The 5725 docs aren't very helpful.

**Comment by ramapcsx2** [comment]
> The 5725 docs aren't very helpful.   
They're awesome, right? :)
First of all, remember that double buffering introduces 16ms (NTSC) more lag.
If that is acceptable to you (I don't like it at all), then you can go ahead.
You will have to define memory regions for buffer A and B. The docs are alright for that part.
Then there are a few bits to toggle on the deinterlacer unit. I don't know them off hand, so you'll have to experiment. I know I had double buffering enabled once. It may have been with a dump of the original firmware programming, as this set does use it.

One more note:
My field rate auto adjustment works very well here. I never notice a screen tear line even in hours of playing. Do you have this mode enabled (the VSync line is connected)?

**Comment by bkoropoff** [comment]
@ramapcsx2 

The vsync locking does reduce the frequency of tearing, but it still happens once in a while.  I don't think the original firmware does double-buffering because I see tearing with it as well, and I've seen other people mention the same thing.  I'm on a V4 unit, so it could be something that changed between revisions.

Do you think it would be possible to actively phase lock the output to the input by continually monitoring the vsync pulses and making adjustments when they start to drift?  I'm not sure if the effect on the screen would be more or less annoying than tearing...

**Comment by ramapcsx2** [comment]
The original firmware does use 2 buffers. It requires them to do deinterlacing.
The chip offers many additional options on how the buffers are used though. It's possible and likely that it doesn't have the speed up / speed down bit set correctly. The docs tell you more about that.

Regarding the locking, I tend towards saying this:
The device already locks to the input continuously. It does this via the (required for operation) H-PLL operation. It working properly can be verified by reseting my sync lock after a minute (Serial Monitor command "."). You'll most likely get no action, since it still refreshes the output within the input window, ie: no drifting occurred.

Here's what I think is going on:
I believe your display has its own 60Hz lock. This would explain the visible tearing you get and would require double buffering to reduce the annoying effect.
Again, it requires correctly setting the speed up / speed down bit. Unless you're using a SNES, it's probably always going to require to "speed up" (to 60Hz). (SNES NTSC outputs at slightly > 60Hz.)

**Comment by istedman** [comment]
Hi,
Been following this for a while, will try the software soon.
Does the screen tearing only happen with a SNES @ 60Hz/NTSC or other platforms?
NTSC is technically 59.94Hz, the typical monitor output is 60Hz, that 0.06Hz difference can mean that every 16.67 seconds, you get a blip as the input and output frames  re-align. I've seen this happen with other video chips.

The Tvia 5725 can scan-convert, there are ways around this, I don't remember exactly how off the top of my head. Have you disabled the interlacer and tried the motion estimation controls?

**Comment by bkoropoff** [comment]
@istedman it happens on both NTSC SNES and Genesis for me.  I've attempted to use the built-in "frame lock" feature in the 5725 (as opposed to the default "free run" mode), but it seems to just produce odd display artifacts.  It's likely I wasn't using it correctly since the documentation doesn't exactly hold your hand.  [This pull request](https://github.com/ramapcsx2/gbs-control/pull/6) eliminates tearing my TV, but other displays might not tolerate it.

**Comment by ramapcsx2** [comment]
In addition to the not-so-great documentation, we use this chip "out of spec" by breaking the deinterlacer unit so it doesn't interfere with 240p processing.
This has a ripple effect to many points the docs talk about, including how the VDS ("video output generator") should be configured.
So you've got to take everything you read in the docs with 2 grains of salt and best just verify things in a test setup.

For this particular issue that @bkoropoff already has a fix for, which I believe will help, I'd like to say that it seems to be affected by the display a lot.
I don't notice it as a problem and in fact, I can only see it if I stare at a very slowly scrolling picture for what feels like minutes. If the picture happened to be static at that time, it would be impossible (here) to see.

**Comment by bkoropoff** [comment]
I'm closing this since active vsync locking is preferable.
