### ISSUE TITLE
RGB input

### ISSUE THREAD

**Issue by tomudo** [ramapcsx2/gbs-control#88]
I use RGBs input via VGA port and 480p. When save preset it show message "open save file failed!"

n function savePresetToSPIFFS when rto->videoStandardInput value is 14, it not save preset.

**Comment by ramapcsx2** [comment]
Yeah, modes 14 and 15 are for VGA / PC sources.
Mode 14 used to be straight RGB bypass, but now with the full processing path, it doesn't have all the required logic to save presets.

I need to think about this.
The problem is that your PC source could present all kinds of formats and resolutions, all the custom preset code is geared towards single / fixed formats though.

**Comment by tomudo** [comment]
My source input is from modded PS2 that output RGB composite sync. It does not really VGA which is RGB HV.

**Comment by ramapcsx2** [comment]
Okay, that's "regular" RGB + CSync then and it should never go into mode 14.
Mode 14 / 15 should only activate if there is an active VSync signal on the VS pin.
This is only possible with a source that has HSync and VSync separately.

**Comment by tomudo** [comment]
I checked the cable and quite sure that nothing wrong with wiring. Only 1 csync signal pin connect to H sync pin (middle of lower pin). V sync pin of VGA has nothing connect. 


Old 18/08/19 commit has no saving problem.

**Comment by ramapcsx2** [comment]
Is it still doing this with the latest version?

**Comment by tomudo** [comment]
Commits on Nov 24, 2019 works. Thank you.

**Comment by ramapcsx2** [comment]
Okay, good to know, but it's still weird that it happened.
I think there might be an edge case that I never run into when testing..

If the bug returns, please tell me :)
