### ISSUE TITLE
Sync Levels and Component input?

### ISSUE THREAD

**Issue by Redphosphors** [ramapcsx2/gbs-control#90]
I have an Extron switcher in my setup and it outputs TTL sync. Can the GBS take it or does it require 75 Ohm csync? Also, can I input a component signal through the VGA port or does it have to be through the RCA jacks?

**Comment by ramapcsx2** [comment]
Sync level on the VGA port can be up to 3.3Vpp, but ideally you'll use 75Ohm sync.   

Component only works through the RCA jacks by default.   
This is because the VGA port green / luma channel isn't hooked up to the SOG input.   
A hardware modification (combining luma with the HSync / CSync input) would enable Component support, but the software would also need to be changed.   
Right now, it's convenient to assume Component will only ever appear on the appropriate input.
