### ISSUE TITLE
Adjust Htotal for active FTL?

### ISSUE THREAD

**Issue by goutsune** [ramapcsx2/gbs-control#96]
Hello there, I'm actually using CRT monitors with GBS hardware and while testing FTL I noticed that I always get either jumping image or squishing image by about 1 line, depending on CRT monitor I use. However I also noticed that adjusting htotal by hand does not seems to noticeably affecy the picture, so I was wondering maybe it's a good idea to use it instead of vtotal?

**Comment by goutsune** [comment]
I just quickly hacked together an option to adjust htotal, never-mind, it is still noticeable with 2 point adjustment. Perhaps more juggling with sync pulse and or front/back porches might alleviate this.

**Comment by ramapcsx2** [comment]
I'll encourage you to experiment :)

**Comment by ramapcsx2** [comment]
Just a heads up:  
The software targets an htotal value that's closer to the source now.  
I've disabled a round down step since it's no longer needed.  
As a side effect, the tear line shows up less often. When it does, it's also less noticeable and it even tends to disappear even before rolling off screen.

**Comment by ramapcsx2** [comment]
No progress here, and the external clock generator option exists now.
